server:
  port: 10002
spring:
  application:
    name: spider
  data:
    elasticsearch:
      cluster-nodes: localhost:9200
      cluster-name: elasticsearch_zhangyong




jdbc:
  url: jdbc:mysql://localhost:3306/spider
  username: root
  password:
  driver: com.mysql.jdbc.Driver

redis:
  host: 127.0.0.1
  port: 6379
  db: 1